language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require "phpunit/phpunit=4.8.6"
  - cp tests/config/main-local.php.sample tests/config/main-local.php
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc

script:
  - phpunit
